import React from 'react'
import { Metadata } from 'next';
import { Box, Stack, Tabs } from '@chakra-ui/react'
import MainWrapper from '@/components/wrapper/MainWrapper';
import PageContent from '@/components/wrapper/PageContent';
import SettingTabs from './Tabs';

interface Props {
  children:React.ReactNode
}

export const metadata: Metadata = {
  title: "Biodata Diri | Tokonyadia",
  description: "Generated by create next app",
  authors: {
    name: 'Wisnu Shena'
  },
  keywords: 'Tokonyadia',
};

const SettingsLayout = ({children}:Props) => {

  return (
    <MainWrapper>
      <PageContent>
        <Stack alignItems={'start'} width={'100%'} gap={'20px'}>
          <SettingTabs />
          {children}
        </Stack>
      </PageContent>
    </MainWrapper>
  )
}

export default SettingsLayout